engine: docker
runtime: runsc
queue_cap: 24 # maximum conccurent jobs
clean_interval: 45 # minutes
repository: "/repository"
submission_configs:
  - id: csharp
    cpu_period: 100000
    cpu_quota: 150000
    max_pids: 256
    max_swap: 0
    max_memory: 64
    timeout: 25 
    container_image: iklabib/kerat:dotnet
    # override container entry point
    entry_point: ["/workspace/box"]

  - id: python
    cpu_period: 100000
    cpu_quota: 150000
    max_pids: 256
    max_swap: 0 
    max_memory: 64
    timeout: 25
    container_image: iklabib/kerat:python
    entry_point: ["python3", "/kerat/main.py" ]
