engine: docker
runtime: runc
queue_cap: 24 # maximum conccurent jobs
clean_interval: 45 # minutes
repository: "/repository"
submission_configs:
  - id: csharp
    cpu_period: 100000
    cpu_quota: 150000
    max_pids: 256
    max_swap: 0
    max_memory: 64
    timeout: 25 
    container_image: iklabib/kerat:box-alpine

  - id: python
    cpu_period: 100000
    cpu_quota: 150000
    max_pids: 256
    max_swap: 0 
    max_memory: 64
    timeout: 25
    container_image: iklabib/kerat:python